### ISSUE TITLE
Add Github issues similar to existing issues for 100 other developer conferences

### ISSUE THREAD

**Issue by jdegoes** [speakers-in-tech/conference-data#20]
Across the top 20 programming languages (as measured by TIOBE, etc.), identify the top 5 conferences for each of these programming languages. Then for each conference, create a Github issue to track adding conference data for the conference, with detailed instructions on what information to collect and how to submit it (as a pull request to the README), suggesting reaching out to the organizers directly for most accurate data.

This ticket will be considered complete when someone has added 100 new Github issues.

**Comment by ziexess** [comment]
Hello @jdegoes,  I'm interested in getting this task done, I'd love to know more information about it regarding if you prefer a particular website for getting the information about top conferences because it can vary depending on individual preferences and priorities.

**Comment by jdegoes** [comment]
I do not know of or prefer a particular website for getting top conferences.

**Comment by ziexess** [comment]
Alright then, I will work on all the 100 conferences and submit them at once. Regarding the additional information about each conference, would you prefer it to be similar to current open issues or prefer any changes?

**Comment by jdegoes** [comment]
Please do add some more details, to make the tickets easier for new contributors to understand and follow.

**Comment by harshbisle** [comment]
Do you also want any specific labels to be added to the issues?

Also, I hope that the issues can include frameworks and library conferences, along with the different countries' variations with the same name on top of the popular programming languages conferences.
