### ISSUE TITLE
Add ScalarConf to conference data tracker

### ISSUE THREAD

**Issue by jdegoes** [speakers-in-tech/conference-data#3]
Add ScalarConf with up-to-date information to the tracking spreadsheet in this repository.

Note: If for any reason an organizer refuses to answer questions, then we should add them to the tracking spreadsheet assuming they are not willing to sign the Speaker Engagement Agreement. They can always correct the information later, if it proves inaccurate.

**Comment by RashulChutani** [comment]
Hi @jdegoes Please review my Pull Request. Thanks.
