### ISSUE TITLE
Add Scala IO to conference data tracker

### ISSUE THREAD

**Issue by jdegoes** [speakers-in-tech/conference-data#5]
Add Scala IO with up-to-date information to the tracking spreadsheet in this repository.

Note: If for any reason an organizer refuses to answer questions, then we should add them to the tracking spreadsheet assuming they are not willing to sign the Speaker Engagement Agreement. They can always correct the information later, if it proves inaccurate.

**Comment by vinfinity7** [comment]
/attempt #5

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clfqycou00006lc0f4lioljtr/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ahoy-jon** [comment]
So:
- I was contacted by a bounty hunter last year by email to reply to questions
- I explained in details why we cannot answer those questions as they are asked
- the bounty is still open, a first attempt where I explain again
- a second attempt with basic mistakes in spelling and correctness
- what's next?

@jdegoes you are personally responsible for wasting a slice of my time with zero added value for the real involved parties.

The data proposed was (with small modifications):
```markdown
[Scala.IO](https://scala.io) | Scala.IO | "Would prefer not to" | Yes | "Full, to the capacity of the funds" | Never |
```
This data is not fitting your expected model.

First, given you insist on the matter, we will make a page about that question on the conference website (FAQ for speakers https://github.com/ScalaIO/scala.io/issues/127).

Then, if you want it to fit your model, you can add Scala.IO with a link to this page.

https://github.com/speakers-in-tech/conference-data/pulls?q=Scala+IO

**Comment by jdegoes** [comment]
Closed at request of @ahoy-jon
