### ISSUE TITLE
Add JSConf to the conference data tracker

### ISSUE THREAD

**Issue by jdegoes** [speakers-in-tech/conference-data#8]
Add JSConf with up-to-date information to the tracking spreadsheet in this repository.

Note: If for any reason an organizer refuses to answer questions, then we should add them to the tracking spreadsheet assuming they are not willing to sign the Speaker Engagement Agreement. They can always correct the information later, if it proves inaccurate.

**Comment by harshbisle** [comment]
Hey, @jdegoes  Please review my PR. Thank You!

**Comment by harshbisle** [comment]
Somehow, I did not receive the bounty. Am I missing something here?
